[package]
name = "display-link"
version = "0.1.0"
authors = ["tyler <tyler@brainiumstudios.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
foreign-types = "0.3.2"

[target.'cfg(any(target_os = "ios"))'.dependencies]
objc = "0.2.5"
objc-foundation = "0.1.1"